import React, { useEffect, useCallback } from 'react';
import { Unity, useUnityContext } from 'react-unity-webgl';

/**
 * UnityGame Component
 * This component hosts the WebGL build of your Unity project.
 * It is designed to be placed in the background of the chat application.
 */
export default function UnityGame({ currentEmotion }) {
  // IMPORTANT: You need to replace these paths with the actual paths generated by Unity WebGL Build
  const { unityProvider, isLoaded, loadingProgression, sendMessage, addEventListener, removeEventListener } = useUnityContext({
    loaderUrl: "/unity/Build/unity-build.loader.js",
    dataUrl: "/unity/Build/unity-build.data",
    frameworkUrl: "/unity/Build/unity-build.framework.js",
    codeUrl: "/unity/Build/unity-build.wasm",
  });

  // Example: Listen for an event sent from Unity to React
  const handleUnityCharacterClicked = useCallback((characterName) => {
    console.log(`Character ${characterName} was clicked in Unity!`);
  }, []);

  useEffect(() => {
    addEventListener("OnCharacterClicked", handleUnityCharacterClicked);
    return () => {
      removeEventListener("OnCharacterClicked", handleUnityCharacterClicked);
    };
  }, [addEventListener, removeEventListener, handleUnityCharacterClicked]);

  // Example: Send an event from React to Unity when emotion changes
  useEffect(() => {
    if (isLoaded && currentEmotion) {
      // SendMessage(GameObject Name, Method Name, Value)
      sendMessage("CharacterManager", "ChangeEmotion", currentEmotion);
    }
  }, [currentEmotion, isLoaded, sendMessage]);

  return (
    <div className="absolute inset-0 z-[-2] pointer-events-auto">
      {!isLoaded && (
        <div className="absolute inset-0 flex items-center justify-center bg-surface-dim">
          <p className="text-primary font-display font-bold animate-pulse">
            Loading Character Realm... {Math.round(loadingProgression * 100)}%
          </p>
        </div>
      )}
      <Unity 
        unityProvider={unityProvider} 
        style={{ width: "100%", height: "100%", visibility: isLoaded ? "visible" : "hidden" }} 
      />
    </div>
  );
}
